# Generated by Django 4.2 on 2024-04-06 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Master', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('DetailEnquiry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialisation', models.CharField(blank=True, max_length=100, null=True)),
                ('duration', models.CharField(blank=True, max_length=100, null=True)),
                ('application_fee', models.CharField(blank=True, max_length=100, null=True)),
                ('tution_fee', models.CharField(blank=True, max_length=100, null=True)),
                ('fee_currency', models.CharField(blank=True, max_length=100, null=True)),
                ('course_link', models.CharField(blank=True, max_length=200, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('ass_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Master.assessment_status')),
                ('assigned_users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('course_interested', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='university', chained_model_field='university', on_delete=django.db.models.deletion.CASCADE, to='Master.course')),
                ('enquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DetailEnquiry.detail_enquiry')),
                ('intake_interested', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Master.intake')),
                ('level_applying_for', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Master.course_levels')),
                ('student_country', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Master.countryinterested')),
                ('university', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='student_country', chained_model_field='country', on_delete=django.db.models.deletion.CASCADE, to='Master.university')),
            ],
        ),
    ]
