# Generated by Django 4.2 on 2024-04-06 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialisation', models.CharField(blank=True, max_length=100, null=True)),
                ('duration', models.CharField(blank=True, max_length=100, null=True)),
                ('application_fee', models.CharField(blank=True, max_length=100, null=True)),
                ('tution_fee', models.CharField(blank=True, max_length=100, null=True)),
                ('fee_currency', models.CharField(blank=True, max_length=100, null=True)),
                ('course_link', models.CharField(blank=True, max_length=200, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
