# Generated by Django 4.2.9 on 2024-04-03 10:12

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('Master', '0011_alter_university_country'),
        ('Assessment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='student_country',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='Master.countryinterested'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assessment',
            name='university',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='student_country', chained_model_field='country', default=1, on_delete=django.db.models.deletion.CASCADE, to='Master.university'),
            preserve_default=False,
        ),
    ]
