# Generated by Django 4.2 on 2024-05-02 04:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('Master', '0001_initial'),
        ('DetailEnquiry', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Assessment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='assigned_users',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='course_interested',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='university', chained_model_field='university', null=True, on_delete=django.db.models.deletion.CASCADE, to='Master.course'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='enquiry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DetailEnquiry.detail_enquiry'),
        ),
    ]
