# Generated by Django 4.2 on 2024-05-28 07:49

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('Master', '0002_alter_enquiryfollowupstatus_user'),
        ('Assessment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='course_interested',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='university', chained_model_field='university', null=True, on_delete=django.db.models.deletion.CASCADE, to='Master.course'),
        ),
    ]
