# Generated by Django 4.2 on 2024-05-28 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Master', '0002_alter_enquiryfollowupstatus_user'),
        ('DetailEnquiry', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Assessment', '0002_alter_assessment_course_interested'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='application_fee',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='ass_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Master.assessment_status'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='assigned_users',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='course_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='duration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='enquiry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DetailEnquiry.detail_enquiry'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='fee_currency',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='intake_interested',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Master.intake'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='level_applying_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Master.course_levels'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='specialisation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='student_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Master.countryinterested'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='tution_fee',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
