# Generated by Django 4.2.9 on 2024-03-22 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Assessment', '0002_alter_assessment_enquiry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assessment',
            old_name='intake_interested_month',
            new_name='intake_interested',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='intake_interested_year',
        ),
    ]
