# Generated by Django 4.2.9 on 2024-04-03 10:13

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('Master', '0011_alter_university_country'),
        ('Assessment', '0002_alter_assessment_student_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='student_country',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='enquiry', chained_model_field='country_interested', on_delete=django.db.models.deletion.CASCADE, to='Master.countryinterested'),
        ),
    ]
