# Generated by Django 4.2 on 2024-04-06 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Assessment', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('DetailEnquiry', '0002_initial'),
        ('Master', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='assigned_users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessment',
            name='course_interested',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='university', chained_model_field='university', on_delete=django.db.models.deletion.CASCADE, to='Master.course'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='enquiry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DetailEnquiry.detail_enquiry'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='intake_interested',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Master.intake'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='level_applying_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Master.course_levels'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='student_country',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Master.countryinterested'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='university',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='student_country', chained_model_field='country', on_delete=django.db.models.deletion.CASCADE, to='Master.university'),
        ),
    ]
