# Generated by Django 4.2.9 on 2024-04-03 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Master', '0011_alter_university_country'),
        ('Assessment', '0003_alter_assessment_student_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='student_country',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Master.countryinterested'),
        ),
    ]
