# Generated by Django 4.2 on 2024-05-03 07:05

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('Master', '0001_initial'),
        ('Assessment', '0003_alter_assessment_student_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='university',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='student_country', chained_model_field='country', null=True, on_delete=django.db.models.deletion.CASCADE, to='Master.university'),
        ),
    ]
