# Generated by Django 4.2 on 2024-04-24 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Assessment', '0004_assessment_followup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='followup',
        ),
    ]
