# Generated by Django 4.2.9 on 2024-04-03 10:37

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('Master', '0011_alter_university_country'),
        ('Assessment', '0004_alter_assessment_student_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='course_interested',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='university', chained_model_field='university', default=1, on_delete=django.db.models.deletion.CASCADE, to='Master.course'),
            preserve_default=False,
        ),
    ]
