# Generated by Django 4.2 on 2024-04-26 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Master', '0006_paymentfollowupstatus_enquiryfollowupstatus_and_more'),
        ('Assessment', '0005_remove_assessment_followup'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='AssesmentFollowup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Master.assesmentfollowupstatus'),
        ),
    ]
