# Generated by Django 4.2 on 2024-04-06 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Master', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('DetailEnquiry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('payment_amount', models.FloatField(blank=True, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_remarks', models.TextField(blank=True, null=True)),
                ('payment_document', models.FileField(blank=True, upload_to='documents/')),
                ('Memo_For', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='DetailEnquiry.detail_enquiry')),
                ('Payment_For', models.ManyToManyField(blank=True, to='Master.available_services')),
                ('Payment_Type', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Master.payment_type')),
                ('payment_mode', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Master.payment_mode')),
                ('payment_received_by', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('payment_status', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Master.payment_status')),
            ],
        ),
    ]
