# Generated by Django 4.2 on 2024-05-09 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Master', '0001_initial'),
        ('DetailEnquiry', '0001_initial'),
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='Memo_For',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DetailEnquiry.detail_enquiry'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='Payment_For',
            field=models.ManyToManyField(blank=True, null=True, to='Master.available_services'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='Payment_Type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Master.payment_type'),
        ),
    ]
