# Generated by Django 4.2 on 2024-04-06 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('DetailEnquiry', '0001_initial'),
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='Memo_For',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='DetailEnquiry.detail_enquiry'),
        ),
    ]
