# Generated by Django 4.2 on 2024-05-09 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Master', '0001_initial'),
        ('Accounts', '0002_alter_payment_memo_for_alter_payment_payment_for_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_mode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Master.payment_mode'),
        ),
    ]
