# Generated by Django 4.2 on 2024-04-06 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Accounts', '0002_initial'),
        ('Master', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='Payment_For',
            field=models.ManyToManyField(blank=True, to='Master.available_services'),
        ),
        migrations.AddField(
            model_name='payment',
            name='Payment_Type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Master.payment_type'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_mode',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Master.payment_mode'),
        ),
    ]
