# Generated by Django 4.2 on 2024-05-21 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Master', '0001_initial'),
        ('Assessment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sop', models.FileField(blank=True, upload_to='sop')),
                ('cv', models.FileField(blank=True, upload_to='cv')),
                ('passport', models.FileField(blank=True, upload_to='passport')),
                ('ielts', models.FileField(blank=True, upload_to='ielts')),
                ('gre', models.FileField(blank=True, upload_to='gre')),
                ('toefl', models.FileField(blank=True, upload_to='toefl')),
                ('gmat', models.FileField(blank=True, upload_to='gmat')),
                ('pte', models.FileField(blank=True, upload_to='pte')),
                ('work_experience', models.FileField(blank=True, upload_to='work_experience')),
                ('diploma_marksheet', models.FileField(blank=True, upload_to='diploma_marksheet')),
                ('bachelor_marksheet', models.FileField(blank=True, upload_to='bachelor_marksheet')),
                ('master_marksheet', models.FileField(blank=True, upload_to='master_marksheet')),
                ('other_documents', models.FileField(blank=True, upload_to='other_documents')),
                ('Rejection_reason', models.TextField(blank=True)),
                ('application', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Assessment.assessment')),
                ('application_status', models.ForeignKey(blank=True, max_length=100, on_delete=django.db.models.deletion.CASCADE, to='Master.application_status')),
            ],
        ),
    ]
