# Generated by Django 4.2 on 2024-05-30 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Master', '0002_alter_enquiryfollowupstatus_user'),
        ('Assessment', '0001_initial'),
        ('Application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='application',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='Assessment.assessment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='application_status',
            field=models.ForeignKey(blank=True, default=1, max_length=100, on_delete=django.db.models.deletion.CASCADE, to='Master.application_status'),
            preserve_default=False,
        ),
    ]
