# Generated by Django 4.2 on 2024-03-26 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Master', '__first__'),
        ('Application', '0001_initial'),
        ('Assessment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Assessment.assessment'),
        ),
        migrations.AddField(
            model_name='application',
            name='application_status',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='Master.application_status'),
        ),
    ]
