# Generated by Django 4.2.9 on 2024-03-22 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Master', '0015_alter_course_course_levels_and_more'),
        ('Application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='application_status',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='Master.application_status'),
        ),
        migrations.AlterField(
            model_name='application',
            name='bachelor_marksheet',
            field=models.FileField(blank=True, null=True, upload_to='bachelor_marksheet'),
        ),
        migrations.AlterField(
            model_name='application',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cv'),
        ),
        migrations.AlterField(
            model_name='application',
            name='diploma_marksheet',
            field=models.FileField(blank=True, null=True, upload_to='diploma_marksheet'),
        ),
        migrations.AlterField(
            model_name='application',
            name='gmat',
            field=models.FileField(blank=True, null=True, upload_to='gmat'),
        ),
        migrations.AlterField(
            model_name='application',
            name='gre',
            field=models.FileField(blank=True, null=True, upload_to='gre'),
        ),
        migrations.AlterField(
            model_name='application',
            name='ielts',
            field=models.FileField(blank=True, null=True, upload_to='ielts'),
        ),
        migrations.AlterField(
            model_name='application',
            name='master_marksheet',
            field=models.FileField(blank=True, null=True, upload_to='master_marksheet'),
        ),
        migrations.AlterField(
            model_name='application',
            name='other_documents',
            field=models.FileField(blank=True, null=True, upload_to='other_documents'),
        ),
        migrations.AlterField(
            model_name='application',
            name='passport',
            field=models.FileField(blank=True, null=True, upload_to='passport'),
        ),
        migrations.AlterField(
            model_name='application',
            name='pte',
            field=models.FileField(blank=True, null=True, upload_to='pte'),
        ),
        migrations.AlterField(
            model_name='application',
            name='sop',
            field=models.FileField(blank=True, null=True, upload_to='sop'),
        ),
        migrations.AlterField(
            model_name='application',
            name='toefl',
            field=models.FileField(blank=True, null=True, upload_to='toefl'),
        ),
        migrations.AlterField(
            model_name='application',
            name='work_experience',
            field=models.FileField(blank=True, null=True, upload_to='work_experience'),
        ),
    ]
