# Generated by Django 4.2 on 2024-05-17 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Master', '0005_alter_detailenquiryfollowupstatus_user'),
        ('Assessment', '0006_alter_assessment_assesmentfollowup_and_more'),
        ('Application', '0002_application_rejection_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='Rejection_reason',
            field=models.TextField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='application',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='Assessment.assessment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='application_status',
            field=models.ForeignKey(blank=True, default=1, max_length=100, on_delete=django.db.models.deletion.CASCADE, to='Master.application_status'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='bachelor_marksheet',
            field=models.FileField(blank=True, default=1, upload_to='bachelor_marksheet'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='cv',
            field=models.FileField(blank=True, default=1, upload_to='cv'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='diploma_marksheet',
            field=models.FileField(blank=True, default=1, upload_to='diploma_marksheet'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='gmat',
            field=models.FileField(blank=True, default=1, upload_to='gmat'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='gre',
            field=models.FileField(blank=True, default=1, upload_to='gre'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='ielts',
            field=models.FileField(blank=True, default=1, upload_to='ielts'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='master_marksheet',
            field=models.FileField(blank=True, default=1, upload_to='master_marksheet'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='other_documents',
            field=models.FileField(blank=True, default=1, upload_to='other_documents'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='passport',
            field=models.FileField(blank=True, default=1, upload_to='passport'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='pte',
            field=models.FileField(blank=True, default=1, upload_to='pte'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='sop',
            field=models.FileField(blank=True, default=1, upload_to='sop'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='toefl',
            field=models.FileField(blank=True, default=1, upload_to='toefl'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='work_experience',
            field=models.FileField(blank=True, default=1, upload_to='work_experience'),
            preserve_default=False,
        ),
    ]
