# Generated by Django 4.2.9 on 2024-03-18 20:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='application_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('App_status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='assessment_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', django_countries.fields.CountryField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='course_levels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('levels', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='course_requirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='current_education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_education', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='documents_required',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docu_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='enquiry_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='intake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intake_month', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='intake_Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intake_year', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='university',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('univ_name', models.CharField(max_length=100)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('univ_desc', models.CharField(max_length=1000)),
                ('univ_logo', models.ImageField(upload_to='media')),
                ('univ_phone', models.CharField(blank=True, max_length=10)),
                ('univ_email', models.EmailField(blank=True, max_length=254)),
                ('univ_website', models.URLField(blank=True)),
                ('assigned_users', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('Active', models.BooleanField()),
                ('course_levels', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Master.course_levels')),
                ('course_requirements', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Master.course_requirements')),
                ('documents_required', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Master.documents_required')),
                ('intake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Master.intake')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Master.university')),
            ],
        ),
    ]
