# Generated by Django 4.2 on 2024-04-30 09:33

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='application_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('App_status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='assessment_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Available_Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Services', models.CharField(max_length=100)),
                ('Price', models.FloatField(blank=True, help_text='Price in INR', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='bachelor_requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', django_countries.fields.CountryField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='CountryInterested',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='course_levels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('levels', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='course_requirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='current_education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_education', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Detail_Enquiry_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='documents_required',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docu_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Duolingo_Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Overall', models.FloatField(validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(160)])),
            ],
        ),
        migrations.CreateModel(
            name='Edu_Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(blank=True, max_length=100, null=True)),
                ('Stream', models.CharField(blank=True, max_length=100, null=True)),
                ('Percentage', models.FloatField(blank=True)),
                ('Year_of_Passing', models.IntegerField(blank=True)),
                ('Name_of_Institute', models.CharField(blank=True, max_length=100)),
                ('Medium_of_Education', models.CharField(blank=True, max_length=100)),
                ('Board', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Enquiry_Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Source', models.CharField(max_length=100)),
                ('Reference_Number', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='enquiry_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Gmat_Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Verbal', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(60)])),
                ('Quantitative', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(60)])),
                ('Analytical', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)])),
                ('Overall', models.FloatField(validators=[django.core.validators.MinValueValidator(200), django.core.validators.MaxValueValidator(800)])),
            ],
        ),
        migrations.CreateModel(
            name='Gre_Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Verbal', models.FloatField(validators=[django.core.validators.MinValueValidator(130), django.core.validators.MaxValueValidator(170)])),
                ('Quantitative', models.FloatField(validators=[django.core.validators.MinValueValidator(130), django.core.validators.MaxValueValidator(170)])),
                ('Analytical', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)])),
                ('Overall', models.FloatField(validators=[django.core.validators.MinValueValidator(260), django.core.validators.MaxValueValidator(340)])),
            ],
        ),
        migrations.CreateModel(
            name='Ielts_Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Listening', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)])),
                ('Reading', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)])),
                ('Writing', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)])),
                ('Speaking', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)])),
                ('Overall', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)])),
            ],
        ),
        migrations.CreateModel(
            name='intake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intake_Name', models.CharField(max_length=100)),
                ('intake_month', models.CharField(max_length=10)),
                ('intake_year', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='masters_requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Payment_Mode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mode', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Payment_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Payment_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PTE_Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Listening', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(90)])),
                ('Reading', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(90)])),
                ('Writing', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(90)])),
                ('Speaking', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(90)])),
                ('Overall', models.FloatField(validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(90)])),
            ],
        ),
        migrations.CreateModel(
            name='Rejection_Reason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Refusal_Reason', models.TextField()),
                ('Refusal_Country', django_countries.fields.CountryField(max_length=2)),
                ('Refusal_Visa_Category', models.CharField(max_length=100)),
                ('Refusal_Date', models.DateField()),
                ('Refusal_Letter', models.FileField(blank=True, upload_to='refusal_letter/')),
            ],
        ),
        migrations.CreateModel(
            name='tenth_std_percentage_requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Toefl_Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Listening', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)])),
                ('Reading', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)])),
                ('Writing', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)])),
                ('Speaking', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)])),
                ('Overall', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)])),
            ],
        ),
        migrations.CreateModel(
            name='twelfth_std_percentage_requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Work_Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company_Name', models.CharField(max_length=100)),
                ('Designation', models.CharField(max_length=100)),
                ('Start_Date', models.DateField()),
                ('End_Date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='university',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('univ_name', models.CharField(max_length=100)),
                ('univ_desc', models.CharField(blank=True, max_length=1000, null=True)),
                ('univ_logo', models.ImageField(blank=True, null=True, upload_to='media')),
                ('univ_phone', models.CharField(blank=True, max_length=10, null=True)),
                ('univ_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('univ_website', models.URLField(blank=True, null=True)),
                ('Remark', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('Active', models.BooleanField()),
                ('newsletter', models.FileField(blank=True, null=True, upload_to='newsletter/', verbose_name='Newsletters')),
                ('application_form', models.FileField(blank=True, null=True, upload_to='application_forms/', verbose_name='Application Form')),
                ('Duolingo_Exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Master.duolingo_exam')),
                ('Gmat_Exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Master.gmat_exam')),
                ('Gre_Exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Master.gre_exam')),
                ('PTE_Exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Master.pte_exam')),
                ('Toefl_Exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Master.toefl_exam')),
                ('assigned_users', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('bachelor_requirement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Master.bachelor_requirement')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Master.countryinterested')),
                ('ielts_Exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Master.ielts_exam')),
                ('masters_requirement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Master.masters_requirement')),
                ('tenth_std_percentage_requirement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Master.tenth_std_percentage_requirement')),
                ('twelfth_std_percentage_requirement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Master.twelfth_std_percentage_requirement')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentFollowupStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_contact_date', models.DateField(blank=True, null=True)),
                ('last_interaction_summary', models.TextField(blank=True)),
                ('last_interaction_type', models.CharField(blank=True, choices=[('call', 'Call'), ('meeting', 'Meeting'), ('email', 'Email'), ('other', 'Other')], max_length=20)),
                ('next_followup_date', models.DateField(blank=True, null=True)),
                ('next_followup_purpose', models.TextField(blank=True)),
                ('next_followup_method', models.CharField(blank=True, choices=[('email', 'Email'), ('phone', 'Phone'), ('sms', 'SMS'), ('other', 'Other')], max_length=20)),
                ('reminder_date_time', models.DateTimeField(blank=True, null=True)),
                ('reminder_frequency', models.CharField(blank=True, choices=[('one-time', 'One-time'), ('daily', 'Daily'), ('weekly', 'Weekly')], max_length=20)),
                ('reminder_notification_method', models.CharField(blank=True, choices=[('email', 'Email'), ('phone', 'Phone'), ('sms', 'SMS'), ('other', 'Other')], max_length=20)),
                ('priority_level', models.CharField(blank=True, choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=20)),
                ('urgency', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('pending', 'Pending'), ('completed', 'Completed')], default='open', max_length=20)),
                ('outcome', models.TextField(blank=True)),
                ('attachment_PaymentFollowup', models.FileField(blank=True, upload_to='attachmentsForPaymentFollowup/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EnquiryFollowupStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_contact_date', models.DateField(blank=True, null=True)),
                ('last_interaction_summary', models.TextField(blank=True)),
                ('last_interaction_type', models.CharField(blank=True, choices=[('call', 'Call'), ('meeting', 'Meeting'), ('email', 'Email'), ('other', 'Other')], max_length=20)),
                ('next_followup_date', models.DateField(blank=True, null=True)),
                ('next_followup_purpose', models.TextField(blank=True)),
                ('next_followup_method', models.CharField(blank=True, choices=[('email', 'Email'), ('phone', 'Phone'), ('sms', 'SMS'), ('other', 'Other')], max_length=20)),
                ('reminder_date_time', models.DateTimeField(blank=True, null=True)),
                ('reminder_frequency', models.CharField(blank=True, choices=[('one-time', 'One-time'), ('daily', 'Daily'), ('weekly', 'Weekly')], max_length=20)),
                ('reminder_notification_method', models.CharField(blank=True, choices=[('email', 'Email'), ('phone', 'Phone'), ('sms', 'SMS'), ('other', 'Other')], max_length=20)),
                ('priority_level', models.CharField(blank=True, choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=20)),
                ('urgency', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('pending', 'Pending'), ('completed', 'Completed')], default='open', max_length=20)),
                ('outcome', models.TextField(blank=True)),
                ('attachment_enquiryFollowup', models.FileField(blank=True, upload_to='attachmentsForEnquiryFollowup/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DetailEnquiryFollowupStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_contact_date', models.DateField(blank=True, null=True)),
                ('last_interaction_summary', models.TextField(blank=True)),
                ('last_interaction_type', models.CharField(blank=True, choices=[('call', 'Call'), ('meeting', 'Meeting'), ('email', 'Email'), ('other', 'Other')], max_length=20)),
                ('next_followup_date', models.DateField(blank=True, null=True)),
                ('next_followup_purpose', models.TextField(blank=True)),
                ('next_followup_method', models.CharField(blank=True, choices=[('email', 'Email'), ('phone', 'Phone'), ('sms', 'SMS'), ('other', 'Other')], max_length=20)),
                ('reminder_date_time', models.DateTimeField(blank=True, null=True)),
                ('reminder_frequency', models.CharField(blank=True, choices=[('one-time', 'One-time'), ('daily', 'Daily'), ('weekly', 'Weekly')], max_length=20)),
                ('reminder_notification_method', models.CharField(blank=True, choices=[('email', 'Email'), ('phone', 'Phone'), ('sms', 'SMS'), ('other', 'Other')], max_length=20)),
                ('priority_level', models.CharField(blank=True, choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=20)),
                ('urgency', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('pending', 'Pending'), ('completed', 'Completed')], default='open', max_length=20)),
                ('outcome', models.TextField(blank=True)),
                ('attachment_DetailEnquiryFollowup', models.FileField(blank=True, upload_to='attachmentsForDetailEnquiryFollowup/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('Remark', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('Active', models.BooleanField()),
                ('Duolingo_Exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Master.duolingo_exam')),
                ('Gmat_Exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Master.gmat_exam')),
                ('Gre_Exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Master.gre_exam')),
                ('PTE_Exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Master.pte_exam')),
                ('Toefl_Exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Master.toefl_exam')),
                ('bachelor_requirement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Master.bachelor_requirement')),
                ('course_levels', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Master.course_levels')),
                ('documents_required', models.ManyToManyField(to='Master.documents_required')),
                ('ielts_Exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Master.ielts_exam')),
                ('intake', models.ManyToManyField(to='Master.intake')),
                ('masters_requirement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Master.masters_requirement')),
                ('tenth_std_percentage_requirement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Master.tenth_std_percentage_requirement')),
                ('twelfth_std_percentage_requirement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Master.twelfth_std_percentage_requirement')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Master.university')),
            ],
        ),
        migrations.CreateModel(
            name='AssesmentFollowupStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_contact_date', models.DateField(blank=True, null=True)),
                ('last_interaction_summary', models.TextField(blank=True)),
                ('last_interaction_type', models.CharField(blank=True, choices=[('call', 'Call'), ('meeting', 'Meeting'), ('email', 'Email'), ('other', 'Other')], max_length=20)),
                ('next_followup_date', models.DateField(blank=True, null=True)),
                ('next_followup_purpose', models.TextField(blank=True)),
                ('next_followup_method', models.CharField(blank=True, choices=[('email', 'Email'), ('phone', 'Phone'), ('sms', 'SMS'), ('other', 'Other')], max_length=20)),
                ('reminder_date_time', models.DateTimeField(blank=True, null=True)),
                ('reminder_frequency', models.CharField(blank=True, choices=[('one-time', 'One-time'), ('daily', 'Daily'), ('weekly', 'Weekly')], max_length=20)),
                ('reminder_notification_method', models.CharField(blank=True, choices=[('email', 'Email'), ('phone', 'Phone'), ('sms', 'SMS'), ('other', 'Other')], max_length=20)),
                ('priority_level', models.CharField(blank=True, choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=20)),
                ('urgency', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('pending', 'Pending'), ('completed', 'Completed')], default='open', max_length=20)),
                ('outcome', models.TextField(blank=True)),
                ('attachment_AssesmentFollowup', models.FileField(blank=True, upload_to='attachmentsForAssesmentFollowup/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
