# Generated by Django 4.2 on 2024-04-09 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Master', '0003_alter_university_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Followup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(choices=[('Enquiry', 'Enquiry'), ('Application', 'Application'), ('Assessment', 'Assessment'), ('Payment', 'Payment')], max_length=100)),
                ('frequency', models.IntegerField(choices=[(1, '1 day'), (2, '2 days'), (3, '3 days')])),
                ('reminder', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
