# Generated by Django 4.2.9 on 2024-03-22 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Master', '0003_university_application_form_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='newsletter',
            field=models.FileField(blank=True, upload_to='newletter/', verbose_name='Newsletters'),
        ),
    ]
