# Generated by Django 4.2 on 2024-03-22 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Master', '0003_rename_overall_gre_exam_overall'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gmat_exam',
            old_name='overall',
            new_name='Overall',
        ),
    ]
