# Generated by Django 4.2 on 2024-04-24 08:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0005_remove_application_followup'),
        ('DetailEnquiry', '0004_remove_detail_enquiry_followup'),
        ('Assessment', '0005_remove_assessment_followup'),
        ('Enquiry', '0006_remove_enquiry_followup_and_more'),
        ('Master', '0004_followup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gmat_exam',
            name='overall',
        ),
        migrations.RemoveField(
            model_name='gre_exam',
            name='overall',
        ),
        migrations.AlterField(
            model_name='duolingo_exam',
            name='Overall',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(160)]),
        ),
        migrations.AlterField(
            model_name='gmat_exam',
            name='Analytical',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)]),
        ),
        migrations.AlterField(
            model_name='gmat_exam',
            name='Quantitative',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(60)]),
        ),
        migrations.AlterField(
            model_name='gmat_exam',
            name='Verbal',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(60)]),
        ),
        migrations.AlterField(
            model_name='gre_exam',
            name='Analytical',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)]),
        ),
        migrations.AlterField(
            model_name='gre_exam',
            name='Quantitative',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(130), django.core.validators.MaxValueValidator(170)]),
        ),
        migrations.AlterField(
            model_name='gre_exam',
            name='Verbal',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(130), django.core.validators.MaxValueValidator(170)]),
        ),
        migrations.AlterField(
            model_name='ielts_exam',
            name='Listening',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.AlterField(
            model_name='ielts_exam',
            name='Overall',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.AlterField(
            model_name='ielts_exam',
            name='Reading',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.AlterField(
            model_name='ielts_exam',
            name='Speaking',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.AlterField(
            model_name='ielts_exam',
            name='Writing',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.AlterField(
            model_name='pte_exam',
            name='Listening',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AlterField(
            model_name='pte_exam',
            name='Overall',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AlterField(
            model_name='pte_exam',
            name='Reading',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AlterField(
            model_name='pte_exam',
            name='Speaking',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AlterField(
            model_name='pte_exam',
            name='Writing',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AlterField(
            model_name='toefl_exam',
            name='Listening',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AlterField(
            model_name='toefl_exam',
            name='Overall',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)]),
        ),
        migrations.AlterField(
            model_name='toefl_exam',
            name='Reading',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AlterField(
            model_name='toefl_exam',
            name='Speaking',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AlterField(
            model_name='toefl_exam',
            name='Writing',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.DeleteModel(
            name='Followup',
        ),
        migrations.AddField(
            model_name='gmat_exam',
            name='Overall',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(200), django.core.validators.MaxValueValidator(800)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gre_exam',
            name='Overall',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(260), django.core.validators.MaxValueValidator(340)]),
            preserve_default=False,
        ),
    ]
