# Generated by Django 4.2 on 2024-03-22 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Master', '0004_rename_overall_gmat_exam_overall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rejection_reason',
            name='Refusal_Reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
