# Generated by Django 4.2 on 2024-05-16 07:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Master', '0004_alter_detailenquiryfollowupstatus_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailenquiryfollowupstatus',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
