# Generated by Django 4.2 on 2024-04-25 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Master', '0005_remove_gmat_exam_overall_remove_gre_exam_overall_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentFollowupStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_contact_date', models.DateField(blank=True, null=True)),
                ('last_interaction_summary', models.TextField(blank=True)),
                ('last_interaction_type', models.CharField(blank=True, choices=[('call', 'Call'), ('meeting', 'Meeting'), ('email', 'Email'), ('other', 'Other')], max_length=20)),
                ('next_followup_date', models.DateField(blank=True, null=True)),
                ('next_followup_purpose', models.TextField(blank=True)),
                ('next_followup_method', models.CharField(blank=True, choices=[('email', 'Email'), ('phone', 'Phone'), ('sms', 'SMS'), ('other', 'Other')], max_length=20)),
                ('reminder_date_time', models.DateTimeField(blank=True, null=True)),
                ('reminder_frequency', models.CharField(blank=True, choices=[('one-time', 'One-time'), ('daily', 'Daily'), ('weekly', 'Weekly')], max_length=20)),
                ('reminder_notification_method', models.CharField(blank=True, choices=[('email', 'Email'), ('phone', 'Phone'), ('sms', 'SMS'), ('other', 'Other')], max_length=20)),
                ('priority_level', models.CharField(blank=True, choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=20)),
                ('urgency', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('pending', 'Pending'), ('completed', 'Completed')], default='open', max_length=20)),
                ('outcome', models.TextField(blank=True)),
                ('attachment_PaymentFollowup', models.FileField(blank=True, upload_to='attachmentsForPaymentFollowup/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EnquiryFollowupStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_contact_date', models.DateField(blank=True, null=True)),
                ('last_interaction_summary', models.TextField(blank=True)),
                ('last_interaction_type', models.CharField(blank=True, choices=[('call', 'Call'), ('meeting', 'Meeting'), ('email', 'Email'), ('other', 'Other')], max_length=20)),
                ('next_followup_date', models.DateField(blank=True, null=True)),
                ('next_followup_purpose', models.TextField(blank=True)),
                ('next_followup_method', models.CharField(blank=True, choices=[('email', 'Email'), ('phone', 'Phone'), ('sms', 'SMS'), ('other', 'Other')], max_length=20)),
                ('reminder_date_time', models.DateTimeField(blank=True, null=True)),
                ('reminder_frequency', models.CharField(blank=True, choices=[('one-time', 'One-time'), ('daily', 'Daily'), ('weekly', 'Weekly')], max_length=20)),
                ('reminder_notification_method', models.CharField(blank=True, choices=[('email', 'Email'), ('phone', 'Phone'), ('sms', 'SMS'), ('other', 'Other')], max_length=20)),
                ('priority_level', models.CharField(blank=True, choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=20)),
                ('urgency', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('pending', 'Pending'), ('completed', 'Completed')], default='open', max_length=20)),
                ('outcome', models.TextField(blank=True)),
                ('attachment_enquiryFollowup', models.FileField(blank=True, upload_to='attachmentsForEnquiryFollowup/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DetailEnquiryFollowupStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_contact_date', models.DateField(blank=True, null=True)),
                ('last_interaction_summary', models.TextField(blank=True)),
                ('last_interaction_type', models.CharField(blank=True, choices=[('call', 'Call'), ('meeting', 'Meeting'), ('email', 'Email'), ('other', 'Other')], max_length=20)),
                ('next_followup_date', models.DateField(blank=True, null=True)),
                ('next_followup_purpose', models.TextField(blank=True)),
                ('next_followup_method', models.CharField(blank=True, choices=[('email', 'Email'), ('phone', 'Phone'), ('sms', 'SMS'), ('other', 'Other')], max_length=20)),
                ('reminder_date_time', models.DateTimeField(blank=True, null=True)),
                ('reminder_frequency', models.CharField(blank=True, choices=[('one-time', 'One-time'), ('daily', 'Daily'), ('weekly', 'Weekly')], max_length=20)),
                ('reminder_notification_method', models.CharField(blank=True, choices=[('email', 'Email'), ('phone', 'Phone'), ('sms', 'SMS'), ('other', 'Other')], max_length=20)),
                ('priority_level', models.CharField(blank=True, choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=20)),
                ('urgency', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('pending', 'Pending'), ('completed', 'Completed')], default='open', max_length=20)),
                ('outcome', models.TextField(blank=True)),
                ('attachment_DetailEnquiryFollowup', models.FileField(blank=True, upload_to='attachmentsForDetailEnquiryFollowup/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AssesmentFollowupStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_contact_date', models.DateField(blank=True, null=True)),
                ('last_interaction_summary', models.TextField(blank=True)),
                ('last_interaction_type', models.CharField(blank=True, choices=[('call', 'Call'), ('meeting', 'Meeting'), ('email', 'Email'), ('other', 'Other')], max_length=20)),
                ('next_followup_date', models.DateField(blank=True, null=True)),
                ('next_followup_purpose', models.TextField(blank=True)),
                ('next_followup_method', models.CharField(blank=True, choices=[('email', 'Email'), ('phone', 'Phone'), ('sms', 'SMS'), ('other', 'Other')], max_length=20)),
                ('reminder_date_time', models.DateTimeField(blank=True, null=True)),
                ('reminder_frequency', models.CharField(blank=True, choices=[('one-time', 'One-time'), ('daily', 'Daily'), ('weekly', 'Weekly')], max_length=20)),
                ('reminder_notification_method', models.CharField(blank=True, choices=[('email', 'Email'), ('phone', 'Phone'), ('sms', 'SMS'), ('other', 'Other')], max_length=20)),
                ('priority_level', models.CharField(blank=True, choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=20)),
                ('urgency', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('pending', 'Pending'), ('completed', 'Completed')], default='open', max_length=20)),
                ('outcome', models.TextField(blank=True)),
                ('attachment_AssesmentFollowup', models.FileField(blank=True, upload_to='attachmentsForAssesmentFollowup/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
