# Generated by Django 4.2.9 on 2024-03-22 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Master', '0005_alter_university_newsletter'),
    ]

    operations = [
        migrations.CreateModel(
            name='bachelor_requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='masters_requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tenth_std_percentage_requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='twelfth_std_percentage_requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_requirements',
        ),
        migrations.RemoveField(
            model_name='university',
            name='duolingo_requirement',
        ),
        migrations.RemoveField(
            model_name='university',
            name='gmat_requirement',
        ),
        migrations.RemoveField(
            model_name='university',
            name='gre_requirement',
        ),
        migrations.RemoveField(
            model_name='university',
            name='ielts_requirement',
        ),
        migrations.RemoveField(
            model_name='university',
            name='pte_requirement',
        ),
        migrations.RemoveField(
            model_name='university',
            name='toefl_requirement',
        ),
        migrations.AddField(
            model_name='course',
            name='Duolingo_Exam',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Master.duolingo_exam'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='Gmat_Exam',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Master.gmat_exam'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='Gre_Exam',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Master.gre_exam'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='PTE_Exam',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Master.pte_exam'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='Toefl_Exam',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Master.toefl_exam'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='ielts_Exam',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Master.ielts_exam'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='university',
            name='Active',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='university',
            name='Duolingo_Exam',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Master.duolingo_exam'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='university',
            name='Gmat_Exam',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Master.gmat_exam'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='university',
            name='Gre_Exam',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Master.gre_exam'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='university',
            name='PTE_Exam',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Master.pte_exam'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='university',
            name='Toefl_Exam',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Master.toefl_exam'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='university',
            name='ielts_Exam',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Master.ielts_exam'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='bachelor_requirement',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Master.bachelor_requirement'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='masters_requirement',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Master.masters_requirement'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='tenth_std_percentage_requirement',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Master.tenth_std_percentage_requirement'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='twelfth_std_percentage_requirement',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Master.twelfth_std_percentage_requirement'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='university',
            name='bachelor_requirement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Master.bachelor_requirement'),
        ),
        migrations.AlterField(
            model_name='university',
            name='masters_requirement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Master.masters_requirement'),
        ),
        migrations.AlterField(
            model_name='university',
            name='tenth_std_percentage_requirement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Master.tenth_std_percentage_requirement'),
        ),
        migrations.AlterField(
            model_name='university',
            name='twelfth_std_percentage_requirement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Master.twelfth_std_percentage_requirement'),
        ),
    ]
