# Generated by Django 4.2 on 2024-04-29 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Master', '0006_paymentfollowupstatus_enquiryfollowupstatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='documents_required',
            field=models.ManyToManyField(to='Master.documents_required'),
        ),
        migrations.AlterField(
            model_name='course',
            name='intake',
            field=models.ManyToManyField(to='Master.intake'),
        ),
    ]
