# Generated by Django 4.2.9 on 2024-03-22 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Master', '0007_university_remark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='university_status',
        ),
        migrations.AddField(
            model_name='course',
            name='Remark',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
    ]
