# Generated by Django 4.2.9 on 2024-04-03 09:55

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Master', '0008_payment_mode_payment_status_payment_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryInterested',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', django_countries.fields.CountryField(max_length=2)),
            ],
        ),
    ]
