# Generated by Django 4.2 on 2024-04-02 13:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Master', '0008_payment_mode_payment_status_payment_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gmat_exam',
            name='overall',
        ),
        migrations.RemoveField(
            model_name='gre_exam',
            name='overall',
        ),
        migrations.RemoveField(
            model_name='ielts_exam',
            name='Overall',
        ),
        migrations.RemoveField(
            model_name='pte_exam',
            name='Overall',
        ),
        migrations.AlterField(
            model_name='duolingo_exam',
            name='Overall',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(160)]),
        ),
        migrations.AlterField(
            model_name='gmat_exam',
            name='Analytical',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)]),
        ),
        migrations.AlterField(
            model_name='gmat_exam',
            name='Quantitative',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(60)]),
        ),
        migrations.AlterField(
            model_name='gmat_exam',
            name='Verbal',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(60)]),
        ),
        migrations.AlterField(
            model_name='gre_exam',
            name='Analytical',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)]),
        ),
        migrations.AlterField(
            model_name='gre_exam',
            name='Quantitative',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(130), django.core.validators.MaxValueValidator(170)]),
        ),
        migrations.AlterField(
            model_name='gre_exam',
            name='Verbal',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(130), django.core.validators.MaxValueValidator(170)]),
        ),
        migrations.AlterField(
            model_name='ielts_exam',
            name='Listening',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.AlterField(
            model_name='ielts_exam',
            name='Reading',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.AlterField(
            model_name='ielts_exam',
            name='Speaking',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.AlterField(
            model_name='ielts_exam',
            name='Writing',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.AlterField(
            model_name='pte_exam',
            name='Listening',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AlterField(
            model_name='pte_exam',
            name='Reading',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AlterField(
            model_name='pte_exam',
            name='Speaking',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AlterField(
            model_name='pte_exam',
            name='Writing',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AlterField(
            model_name='tenth_std_percentage_requirement',
            name='percentage',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='toefl_exam',
            name='Listening',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AlterField(
            model_name='toefl_exam',
            name='Overall',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)]),
        ),
        migrations.AlterField(
            model_name='toefl_exam',
            name='Reading',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AlterField(
            model_name='toefl_exam',
            name='Speaking',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AlterField(
            model_name='toefl_exam',
            name='Writing',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AlterField(
            model_name='twelfth_std_percentage_requirement',
            name='percentage',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='gmat_exam',
            name='Overall',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(200), django.core.validators.MaxValueValidator(800)]),
        ),
        migrations.AddField(
            model_name='gre_exam',
            name='Overall',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(260), django.core.validators.MaxValueValidator(340)]),
        ),
        migrations.AddField(
            model_name='ielts_exam',
            name='overall',
            field=models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(9)]),
        ),
    ]
