# Generated by Django 4.2.9 on 2024-03-22 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Master', '0009_delete_intake_year_intake_intake_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='documents_required',
        ),
        migrations.AddField(
            model_name='course',
            name='documents_required',
            field=models.ManyToManyField(blank=True, to='Master.documents_required'),
        ),
    ]
