# Generated by Django 4.2 on 2024-04-04 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Master', '0009_remove_gmat_exam_overall_remove_gre_exam_overall_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryInterested',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
