# Generated by Django 4.2.9 on 2024-03-22 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Master', '0010_remove_course_documents_required_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rejection_reason',
            name='Refusal_Letter',
            field=models.FileField(blank=True, upload_to='refusal_letter/'),
        ),
        migrations.AlterField(
            model_name='university',
            name='Duolingo_Exam',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Master.duolingo_exam'),
        ),
        migrations.AlterField(
            model_name='university',
            name='Gmat_Exam',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Master.gmat_exam'),
        ),
        migrations.AlterField(
            model_name='university',
            name='Gre_Exam',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Master.gre_exam'),
        ),
        migrations.AlterField(
            model_name='university',
            name='PTE_Exam',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Master.pte_exam'),
        ),
        migrations.AlterField(
            model_name='university',
            name='Toefl_Exam',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Master.toefl_exam'),
        ),
        migrations.AlterField(
            model_name='university',
            name='bachelor_requirement',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Master.bachelor_requirement'),
        ),
        migrations.AlterField(
            model_name='university',
            name='ielts_Exam',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Master.ielts_exam'),
        ),
        migrations.AlterField(
            model_name='university',
            name='masters_requirement',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Master.masters_requirement'),
        ),
        migrations.AlterField(
            model_name='university',
            name='tenth_std_percentage_requirement',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Master.tenth_std_percentage_requirement'),
        ),
        migrations.AlterField(
            model_name='university',
            name='twelfth_std_percentage_requirement',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Master.twelfth_std_percentage_requirement'),
        ),
    ]
