# Generated by Django 4.2.9 on 2024-03-22 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Master', '0011_rejection_reason_refusal_letter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='univ_logo',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
