# Generated by Django 4.2.9 on 2024-03-22 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Master', '0013_alter_course_bachelor_requirement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Duolingo_Exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Master.duolingo_exam'),
        ),
        migrations.AlterField(
            model_name='course',
            name='Gmat_Exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Master.gmat_exam'),
        ),
        migrations.AlterField(
            model_name='course',
            name='Gre_Exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Master.gre_exam'),
        ),
        migrations.AlterField(
            model_name='course',
            name='PTE_Exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Master.pte_exam'),
        ),
        migrations.AlterField(
            model_name='course',
            name='Remark',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='course',
            name='Toefl_Exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Master.toefl_exam'),
        ),
        migrations.AlterField(
            model_name='course',
            name='ielts_Exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Master.ielts_exam'),
        ),
        migrations.AlterField(
            model_name='course',
            name='masters_requirement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Master.masters_requirement'),
        ),
        migrations.AlterField(
            model_name='course',
            name='tenth_std_percentage_requirement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Master.tenth_std_percentage_requirement'),
        ),
        migrations.AlterField(
            model_name='course',
            name='twelfth_std_percentage_requirement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Master.twelfth_std_percentage_requirement'),
        ),
        migrations.AlterField(
            model_name='university',
            name='Duolingo_Exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Master.duolingo_exam'),
        ),
        migrations.AlterField(
            model_name='university',
            name='Gmat_Exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Master.gmat_exam'),
        ),
        migrations.AlterField(
            model_name='university',
            name='Gre_Exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Master.gre_exam'),
        ),
        migrations.AlterField(
            model_name='university',
            name='PTE_Exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Master.pte_exam'),
        ),
        migrations.AlterField(
            model_name='university',
            name='Remark',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='university',
            name='Toefl_Exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Master.toefl_exam'),
        ),
        migrations.AlterField(
            model_name='university',
            name='application_form',
            field=models.FileField(blank=True, null=True, upload_to='application_forms/', verbose_name='Application Form'),
        ),
        migrations.AlterField(
            model_name='university',
            name='assigned_users',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='university',
            name='ielts_Exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Master.ielts_exam'),
        ),
        migrations.AlterField(
            model_name='university',
            name='masters_requirement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Master.masters_requirement'),
        ),
        migrations.AlterField(
            model_name='university',
            name='newsletter',
            field=models.FileField(blank=True, null=True, upload_to='newsletter/', verbose_name='Newsletters'),
        ),
    ]
