# Generated by Django 4.2.9 on 2024-03-22 11:07

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Master', '0014_alter_course_duolingo_exam_alter_course_gmat_exam_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_levels',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Master.course_levels'),
        ),
        migrations.AlterField(
            model_name='course',
            name='documents_required',
            field=models.ManyToManyField(blank=True, null=True, to='Master.documents_required'),
        ),
        migrations.AlterField(
            model_name='course',
            name='intake',
            field=models.ManyToManyField(blank=True, null=True, to='Master.intake'),
        ),
        migrations.AlterField(
            model_name='university',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='tenth_std_percentage_requirement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Master.tenth_std_percentage_requirement'),
        ),
        migrations.AlterField(
            model_name='university',
            name='twelfth_std_percentage_requirement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Master.twelfth_std_percentage_requirement'),
        ),
        migrations.AlterField(
            model_name='university',
            name='univ_desc',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='univ_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='univ_logo',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='university',
            name='univ_phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='univ_website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
