# Generated by Django 4.2.9 on 2024-03-22 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Master', '0015_alter_course_course_levels_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ielts_exam',
            name='Listening',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ielts_exam',
            name='Overall',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ielts_exam',
            name='Reading',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ielts_exam',
            name='Speaking',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ielts_exam',
            name='Writing',
            field=models.FloatField(null=True),
        ),
    ]
