# Generated by Django 4.2 on 2024-04-06 11:50

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_First_Name', models.CharField(max_length=100)),
                ('student_Last_Name', models.CharField(max_length=100)),
                ('student_passport', models.CharField(max_length=100)),
                ('student_phone', models.CharField(max_length=10)),
                ('alternate_phone', models.CharField(max_length=10)),
                ('student_email', models.EmailField(max_length=254)),
                ('student_address', models.TextField()),
                ('student_country', django_countries.fields.CountryField(default='IN', max_length=2)),
                ('student_state', models.CharField(max_length=100)),
                ('student_city', models.CharField(max_length=100)),
                ('student_zip', models.CharField(max_length=10)),
                ('notes', models.TextField()),
            ],
        ),
    ]
