# Generated by Django 4.2 on 2024-03-22 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Enquiry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='alternate_phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='student_address',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='student_email',
            field=models.EmailField(max_length=100),
        ),
    ]
