# Generated by Django 4.2 on 2024-04-06 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Enquiry', '0001_initial'),
        ('Master', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='Interested_Services',
            field=models.ManyToManyField(blank=True, default='Counselling', related_name='Interested_Services', to='Master.available_services'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='Source_Enquiry',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Master.enquiry_source'),
        ),
    ]
