# Generated by Django 4.2.9 on 2024-03-22 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Enquiry', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquiry',
            old_name='intake_interested_month',
            new_name='intake_interested',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='intake_interested_year',
        ),
    ]
