# Generated by Django 4.2 on 2024-04-06 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Master', '0001_initial'),
        ('Enquiry', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='assigned_users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='country_interested',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Master.countryinterested'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='course_interested',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='university_interested', chained_model_field='university', on_delete=django.db.models.deletion.CASCADE, to='Master.course'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='current_education',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Master.current_education'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='enquiry_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Master.enquiry_status'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='intake_interested',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Master.intake'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='level_applying_for',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Master.course_levels'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='university_interested',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='country_interested', chained_model_field='country', on_delete=django.db.models.deletion.CASCADE, to='Master.university'),
        ),
    ]
