# Generated by Django 4.2 on 2024-04-30 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Enquiry', '0002_alter_enquiry_source_enquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='assigned_users',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
