# Generated by Django 4.2 on 2024-04-30 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Master', '0001_initial'),
        ('Enquiry', '0003_alter_enquiry_assigned_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='country_interested',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Master.countryinterested'),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='intake_interested',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Master.intake'),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='level_applying_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Master.course_levels'),
        ),
    ]
