# Generated by Django 4.2 on 2024-04-06 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Master', '0002_initial'),
        ('Enquiry', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='Source_Enquiry',
            field=models.ForeignKey(blank=True, default='Website', on_delete=django.db.models.deletion.CASCADE, to='Master.enquiry_source'),
        ),
    ]
