# Generated by Django 4.2 on 2024-04-09 12:07

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('Master', '0003_alter_university_country'),
        ('Enquiry', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='Source_Enquiry',
            field=models.ForeignKey(blank=True, default='Website', on_delete=django.db.models.deletion.CASCADE, to='Master.enquiry_source'),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='course_interested',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='university_interested', chained_model_field='university', null=True, on_delete=django.db.models.deletion.CASCADE, to='Master.course'),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='university_interested',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='country_interested', chained_model_field='country', on_delete=django.db.models.deletion.CASCADE, to='Master.university'),
        ),
    ]
