# Generated by Django 4.2 on 2024-04-09 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Master', '0004_followup'),
        ('Enquiry', '0004_alter_enquiry_source_enquiry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='followup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Master.followup'),
        ),
    ]
