# Generated by Django 4.2 on 2024-04-24 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Enquiry', '0005_enquiry_followup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='followup',
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='alternate_phone',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='student_phone',
            field=models.CharField(max_length=100),
        ),
    ]
