# Generated by Django 4.2 on 2024-04-06 12:24

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('Master', '0003_alter_university_country'),
        ('Enquiry', '0005_alter_enquiry_course_interested'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='university_interested',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='country_interested', chained_model_field='country', on_delete=django.db.models.deletion.CASCADE, to='Master.university'),
        ),
    ]
