# Generated by Django 4.2 on 2024-04-30 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Master', '0001_initial'),
        ('Enquiry', '0005_alter_enquiry_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='current_education',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Master.current_education'),
        ),
    ]
