# Generated by Django 4.2 on 2024-04-30 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Master', '0001_initial'),
        ('Enquiry', '0006_alter_enquiry_current_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='enquiry_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Master.enquiry_status'),
        ),
    ]
