# Generated by Django 4.2 on 2024-04-30 10:03

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('Master', '0001_initial'),
        ('Enquiry', '0007_alter_enquiry_enquiry_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='university_interested',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='country_interested', chained_model_field='country', null=True, on_delete=django.db.models.deletion.CASCADE, to='Master.university'),
        ),
    ]
