# Generated by Django 4.2 on 2024-04-02 13:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Enquiry', '0011_alter_enquiry_source_enquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='student_zip',
            field=models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(6), django.core.validators.MaxLengthValidator(10)]),
        ),
    ]
