# Generated by Django 4.2.9 on 2024-04-03 09:50

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('Master', '0008_payment_mode_payment_status_payment_type'),
        ('Enquiry', '0011_alter_enquiry_source_enquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='university_interested',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='country_interested', chained_model_field='country', default='University of Oxford', on_delete=django.db.models.deletion.CASCADE, to='Master.university'),
        ),
    ]
