# Generated by Django 4.2.9 on 2024-04-03 09:55

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('Master', '0009_countryinterested'),
        ('Enquiry', '0012_alter_enquiry_university_interested'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='country_interested',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Master.countryinterested'),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='university_interested',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='country_interested', chained_model_field='country', on_delete=django.db.models.deletion.CASCADE, to='Master.university'),
        ),
    ]
