# Generated by Django 4.2.9 on 2024-04-03 10:07

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('Master', '0011_alter_university_country'),
        ('Enquiry', '0013_alter_enquiry_country_interested_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='course_interested',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='university_interested', chained_model_field='university', on_delete=django.db.models.deletion.CASCADE, to='Master.course'),
        ),
    ]
