# Generated by Django 4.2 on 2024-04-04 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Enquiry', '0012_continent_country_location'),
        ('Enquiry', '0014_alter_enquiry_course_interested'),
    ]

    operations = [
    ]
