# Generated by Django 4.2.9 on 2024-04-04 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Enquiry', '0015_merge_20240404_0725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='continent',
        ),
        migrations.RemoveField(
            model_name='location',
            name='continent',
        ),
        migrations.RemoveField(
            model_name='location',
            name='country',
        ),
        migrations.DeleteModel(
            name='Continent',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
