# Generated by Django 4.2.9 on 2024-04-04 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Master', '0011_alter_university_country'),
        ('Enquiry', '0019_alter_enquiry_level_applying_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='level_applying_for',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Master.course_levels'),
        ),
    ]
