# Generated by Django 4.2 on 2024-04-06 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Master', '0001_initial'),
        ('Enquiry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail_Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Father_Occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('Father_Annual_Income', models.FloatField(blank=True, null=True)),
                ('Twelveth_Document', models.FileField(blank=True, upload_to='documents/')),
                ('Tenth_Document', models.FileField(blank=True, upload_to='documents/')),
                ('Graduation_Marksheet', models.FileField(blank=True, upload_to='documents/')),
                ('Graduation_Certificate', models.FileField(blank=True, upload_to='documents/')),
                ('UG_Marksheet', models.FileField(blank=True, upload_to='documents/')),
                ('UG_Certificate', models.FileField(blank=True, upload_to='documents/')),
                ('Work_Experience_Document', models.FileField(blank=True, upload_to='documents/')),
                ('Passport_Document', models.FileField(blank=True, upload_to='documents/')),
                ('Offer_Letter', models.FileField(blank=True, upload_to='documents/')),
                ('Ielts_Result', models.FileField(blank=True, upload_to='documents/')),
                ('Toefl_Result', models.FileField(blank=True, upload_to='documents/')),
                ('PTE_Result', models.FileField(blank=True, upload_to='documents/')),
                ('Duolingo_Result', models.FileField(blank=True, upload_to='documents/')),
                ('Gre_Result', models.FileField(blank=True, upload_to='documents/')),
                ('Gmat_Result', models.FileField(blank=True, upload_to='documents/')),
                ('Confirmed_Services', models.ManyToManyField(blank=True, to='Master.available_services')),
                ('Current_Education_Details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Master.edu_level')),
                ('Current_Enquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Enquiry.enquiry')),
                ('Duolingo_Exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Master.duolingo_exam')),
                ('Enquiry_Status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Master.detail_enquiry_status')),
                ('Gmat_Exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Master.gmat_exam')),
                ('Graduation_Education_Details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Graduation_Education_Details', to='Master.edu_level')),
                ('Gre_Exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Master.gre_exam')),
                ('PTE_Exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Master.pte_exam')),
                ('Refusal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Master.rejection_reason')),
                ('Tenth_Education_Details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Tenth_Education_Details', to='Master.edu_level')),
                ('Toefl_Exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Master.toefl_exam')),
                ('Twelveth_Education_Details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Twelveth_Education_Details', to='Master.edu_level')),
                ('Work_Experience', models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='Master.work_experience')),
                ('ielts_Exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Master.ielts_exam')),
            ],
        ),
    ]
