# Generated by Django 4.2.9 on 2024-03-20 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Master', '0002_duolingo_exam_edu_level_gmat_exam_gre_exam_and_more'),
        ('Enquiry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail_Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Father_Occupation', models.CharField(max_length=100)),
                ('Father_Annual_Income', models.FloatField()),
                ('Twelveth_Document', models.FileField(upload_to='documents/')),
                ('Tenth_Document', models.FileField(upload_to='documents/')),
                ('Graduation_Marksheet', models.FileField(upload_to='documents/')),
                ('Graduation_Certificate', models.FileField(upload_to='documents/')),
                ('UG_Marksheet', models.FileField(upload_to='documents/')),
                ('UG_Certificate', models.FileField(upload_to='documents/')),
                ('Work_Experience_Document', models.FileField(upload_to='documents/')),
                ('Passport_Document', models.FileField(upload_to='documents/')),
                ('Offer_Letter', models.FileField(upload_to='documents/')),
                ('Ielts_Result', models.FileField(upload_to='documents/')),
                ('Toefl_Result', models.FileField(upload_to='documents/')),
                ('PTE_Result', models.FileField(upload_to='documents/')),
                ('Duolingo_Result', models.FileField(upload_to='documents/')),
                ('Gre_Result', models.FileField(upload_to='documents/')),
                ('Gmat_Result', models.FileField(upload_to='documents/')),
                ('Current_Enquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Enquiry.enquiry')),
                ('Duolingo_Exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Master.duolingo_exam')),
                ('Gmat_Exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Master.gmat_exam')),
                ('Gre_Exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Master.gre_exam')),
                ('PTE_Exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Master.pte_exam')),
                ('Refusal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Master.rejection_reason')),
                ('Toefl_Exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Master.toefl_exam')),
                ('Work_Experience', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='Master.work_experience')),
                ('ielts_Exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Master.ielts_exam')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Master.edu_level')),
            ],
        ),
    ]
