# Generated by Django 4.2 on 2024-04-06 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Enquiry', '0001_initial'),
        ('DetailEnquiry', '0001_initial'),
        ('Master', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail_enquiry',
            name='Confirmed_Services',
            field=models.ManyToManyField(blank=True, to='Master.available_services'),
        ),
        migrations.AddField(
            model_name='detail_enquiry',
            name='Current_Education_Details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Master.edu_level'),
        ),
        migrations.AddField(
            model_name='detail_enquiry',
            name='Current_Enquiry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Enquiry.enquiry'),
        ),
        migrations.AddField(
            model_name='detail_enquiry',
            name='Duolingo_Exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Master.duolingo_exam'),
        ),
        migrations.AddField(
            model_name='detail_enquiry',
            name='Enquiry_Status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Master.detail_enquiry_status'),
        ),
        migrations.AddField(
            model_name='detail_enquiry',
            name='Gmat_Exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Master.gmat_exam'),
        ),
        migrations.AddField(
            model_name='detail_enquiry',
            name='Graduation_Education_Details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Graduation_Education_Details', to='Master.edu_level'),
        ),
        migrations.AddField(
            model_name='detail_enquiry',
            name='Gre_Exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Master.gre_exam'),
        ),
        migrations.AddField(
            model_name='detail_enquiry',
            name='PTE_Exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Master.pte_exam'),
        ),
        migrations.AddField(
            model_name='detail_enquiry',
            name='Refusal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Master.rejection_reason'),
        ),
        migrations.AddField(
            model_name='detail_enquiry',
            name='Tenth_Education_Details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Tenth_Education_Details', to='Master.edu_level'),
        ),
        migrations.AddField(
            model_name='detail_enquiry',
            name='Toefl_Exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Master.toefl_exam'),
        ),
        migrations.AddField(
            model_name='detail_enquiry',
            name='Twelveth_Education_Details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Twelveth_Education_Details', to='Master.edu_level'),
        ),
        migrations.AddField(
            model_name='detail_enquiry',
            name='Work_Experience',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='Master.work_experience'),
        ),
        migrations.AddField(
            model_name='detail_enquiry',
            name='ielts_Exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Master.ielts_exam'),
        ),
    ]
