# Generated by Django 4.2 on 2024-06-04 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Enquiry', '0001_initial'),
        ('DetailEnquiry', '0004_alter_detail_enquiry_current_education_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail_enquiry',
            name='Current_Enquiry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Enquiry.enquiry'),
        ),
    ]
