# Generated by Django 4.2 on 2024-04-25 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Enquiry', '0006_remove_enquiry_followup_and_more'),
        ('DetailEnquiry', '0004_remove_detail_enquiry_followup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail_enquiry',
            name='Current_Enquiry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Enquiry.enquiry'),
        ),
    ]
