# Generated by Django 4.2 on 2024-04-26 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Master', '0006_paymentfollowupstatus_enquiryfollowupstatus_and_more'),
        ('DetailEnquiry', '0006_detail_enquiry_detaienquiryfollowup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail_enquiry',
            name='Confirmed_Services',
            field=models.ManyToManyField(to='Master.available_services'),
        ),
    ]
