# Generated by Django 4.2 on 2024-04-29 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Master', '0007_alter_course_documents_required_alter_course_intake'),
        ('DetailEnquiry', '0007_alter_detail_enquiry_confirmed_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail_enquiry',
            name='Confirmed_Services',
            field=models.ManyToManyField(blank=True, to='Master.available_services'),
        ),
    ]
